# Generated by Django 3.0.5 on 2024-02-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20240201_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='time_limit_minutes',
        ),
        migrations.AddField(
            model_name='course',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
