# Generated by Django 3.0.5 on 2024-02-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20240201_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_time',
            field=models.PositiveIntegerField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
