# Generated by Django 3.0.5 on 2024-02-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_course_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_time',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=5555),
        ),
    ]
